### PR TITLE
fix: do not update yaml association until user sets file pattern

### LINKED ISSUE #73: VSCode Config being created / amended in unrelated projects
When I open a project in VSCode, a new local settings file is created with the Maestro Workbench config.

This behaviour is a bit unusual, and shouldn't happen for non-Maestro projects.

Image

### PR DESCRIPTION
**Pull request by Mastersam07**
Fixes #73

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -102,9 +104,6 @@ export function activate(context: vscode.ExtensionContext) {
 	});
 
 	context.subscriptions.push(listDevicesCommand);
-
-	const schemaPath = vscode.Uri.file(path.join(context.extensionPath, "schema", "schema.v0.json")).toString();
-	updateYamlSchemaAssociations(schemaPath);
```
Comment (Fishbowler) [inline src/extension.ts:107]: This call no longer exists within this method. Intentional?

If so, when is schemaPath now used?

Comment (Mastersam07) [reply src/extension.ts:107]: Line 40 - 46. Couldn't find how to get a permalink to it.

When the filePatterns are updated, we `updateYamlSchemaAssociations` and also `updateFileWatcherAndTreeView `

**Review by Fishbowler — APPROVED** [review]
