### PR TITLE
fix: show files that matches configured file patterns in tree view

### LINKED ISSUE #65: Tree view won't display as shown in extension
I like the extension and would like to use the tree viewer to easily navigate through linked files.  
However the Maestro workbench tree viewer also shows other files like .MD and .JS files. 

It is just like the normal explorer only with the root being the .maestro folder. I tried playing with the file patterns, even when I point it to a specific test folder with yaml files in it I will see the whole .maestro folder in the maestro workbench tree viewer. If I delete all File patterns the Maestro workbench tree view is empty. 

So it is looking at the patterns but not filtering correctly, is there something I am missing or is this a bug?

**Example:**

1.  Without file patterns: no files in the maestro workbench tree viewer
2. With only **.maestro/flows/subject/*.yaml** the tree viewer shows the whole .maestro map and files in it.

### PR DESCRIPTION
**Pull request by Mastersam07**
Fixes #65 

https://github.com/user-attachments/assets/ff23fc75-f58c-46f0-82bd-742e83f549b5

### CODE REVIEW

File: src/provider/treeView.ts [hunk 1]
```diff
@@ -154,33 +173,36 @@ export class MaestroWorkBenchTreeViewProvider implements vscode.TreeDataProvider
...
+                    const parsed = doc.toJS();
+                    const flows = Array.isArray(parsed) ? parsed : [parsed];
+
+                    flows.forEach((flow) => {
+                        if (!flow) return;
+
+                        if (flow.runFlow && flow.runFlow.file) {
+                            const dependencyPath = path.resolve(path.dirname(filePath), flow.runFlow.file);
+                            dependencies.add(dependencyPath);
+                        }
```
Comment (Fishbowler) [inline src/provider/treeView.ts:185]: Does this account for the short format? e.g. `- runFlow: 'someFile.yaml'`

File: src/provider/treeView.ts [hunk 2]
```diff
@@ -154,33 +173,36 @@ export class MaestroWorkBenchTreeViewProvider implements vscode.TreeDataProvider
...
-                                        dependencies.add(dependencyPath);
-                                    });
-                                }
+                    const parsed = doc.toJS();
+                    const flows = Array.isArray(parsed) ? parsed : [parsed];
+
+                    flows.forEach((flow) => {
+                        if (!flow) return;
+
+                        if (flow.runFlow && flow.runFlow.file) {
```
Comment (Fishbowler) [inline src/provider/treeView.ts:182]: Does this need to account for runFlow containing a list of `commands` which could contain dependencies?

File: src/provider/treeView.ts [hunk 3]
```diff
@@ -154,33 +173,36 @@ export class MaestroWorkBenchTreeViewProvider implements vscode.TreeDataProvider
...
+                            const dependencyPath = path.resolve(path.dirname(filePath), flow.runFlow.file);
+                            dependencies.add(dependencyPath);
+                        }
+
+                        if (flow.runScript && flow.runScript.file) {
```
Comment (Fishbowler) [inline src/provider/treeView.ts:187]: Short format again?

File: src/provider/treeView.ts [hunk 4]
```diff
@@ -154,33 +173,36 @@ export class MaestroWorkBenchTreeViewProvider implements vscode.TreeDataProvider
...
-                                } else if (flow.addMedia.files && Array.isArray(flow.addMedia.files)) {
-                                    flow.addMedia.files.forEach((mediaFile: string) => {
-                                        const dependencyPath = path.resolve(path.dirname(filePath), mediaFile);
-                                        dependencies.add(dependencyPath);
-                                    });
-                                }
+                    const parsed = doc.toJS();
+                    const flows = Array.isArray(parsed) ? parsed : [parsed];
+
+                    flows.forEach((flow) => {
```
Comment (Fishbowler) [inline src/provider/treeView.ts:179]: This misses retry.file

Also, does this account for various places a command that has a file could be introduced?

e.g. we could have a runFlow/runScript/addMedia/retry in:
* onFlowStart
* onFlowComplete
* runFlow > commands (as noted below)
* repeat > commands
* retry > commands

And there's the potential of recursion too....

**Review by Fishbowler — COMMENTED** [review]
Some comments on completeness of the searching

File: src/provider/treeView.ts (hunk 1 above)
Comment (Fishbowler) [reply src/provider/treeView.ts:185]: Just tested, it doesn't.

Comment (Mastersam07) [reply src/provider/treeView.ts:185]: It doesn't. Will update this PR

File: src/provider/treeView.ts (hunk 3 above)
Comment (Mastersam07) [reply src/provider/treeView.ts:187]: It doesn't. Will update this PR

File: src/provider/treeView.ts (hunk 2 above)
Comment (Mastersam07) [reply src/provider/treeView.ts:182]: Tricky.

Comment (Fishbowler) [reply src/provider/treeView.ts:182]: Recursive something something? 😬

File: src/provider/treeView.ts (hunk 4 above)
Comment (Mastersam07) [reply src/provider/treeView.ts:179]: Trying to keep this PR as focused as possible to this issue. I touched analyse dependency since it seems to have broken(based on the original written implementation).

Perhaps we should take conversation for dependencies to #77 ? I am working on analyze dependencies proper there since we would need it before we can close #72

**Review by Fishbowler — APPROVED** [review]
This fixes the issue for this repository.

With a config including `"maestroWorkbench.filePatterns": ["tests/examples/*.yaml"]`, I had this experience:

Before - the 3 flow files appeared, but so did the typescript test file that uses them

After - the test file disappears, but the flows remain, as do a bunch of the files they reference (along with indicators that they're missing)

image

_Will push that config to this branch_

**Comment by Fishbowler** [comment]
The stuff for #77:

* Deal with short format commands
* Add retry.file
* Account for file-hosting commands in:
  * onFlowStart
  * onFlowComplete
  * runFlow > commands (as noted below)
  * repeat > commands
  * retry > commands
* Account for recursion in the above
